/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brochures: Brochure;
    'lighting-presets': LightingPreset;
    'three-d-assets': ThreeDAsset;
    pages: Page;
    'landing-pages': LandingPage;
    'blog-posts': BlogPost;
    'case-studies': CaseStudy;
    capabilities: Capability;
    machines: Machine;
    industries: Industry;
    'product-families': ProductFamily;
    products: Product;
    materials: Material;
    finishes: Finish;
    applications: Application;
    leads: Lead;
    rfqs: Rfq;
    'form-submissions': FormSubmission;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brochures: BrochuresSelect<false> | BrochuresSelect<true>;
    'lighting-presets': LightingPresetsSelect<false> | LightingPresetsSelect<true>;
    'three-d-assets': ThreeDAssetsSelect<false> | ThreeDAssetsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    machines: MachinesSelect<false> | MachinesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'product-families': ProductFamiliesSelect<false> | ProductFamiliesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    finishes: FinishesSelect<false> | FinishesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    rfqs: RfqsSelect<false> | RfqsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
    'social-links': SocialLink;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brochures".
 */
export interface Brochure {
  id: number;
  title: string;
  slug: string;
  brochureType?:
    | (
        | 'company-profile'
        | 'product-catalogue'
        | 'capability-brochure'
        | 'industry-brochure'
        | 'technical-data-sheet'
        | 'other'
      )
    | null;
  summary?: string | null;
  coverImage?: (number | null) | Media;
  products?: (number | Product)[] | null;
  industries?: (number | Industry)[] | null;
  capabilities?: (number | Capability)[] | null;
  isPublic?: boolean | null;
  requiresLeadCapture?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  sku?: string | null;
  productType?: ('standard' | 'configurable' | 'custom' | 'service') | null;
  productFamily?: (number | null) | ProductFamily;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Category path shown above the title, e.g. "Aviation / GSE / Stands".
   */
  breadcrumb?: string | null;
  /**
   * Shown as "Industry: …" in the overview.
   */
  industryLabel?: string | null;
  /**
   * Shown as "Category: …" in the overview.
   */
  categoryLabel?: string | null;
  /**
   * Short label/value pairs shown beside the description (Type, Material, Weight, Capacity, …).
   */
  keySpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Images used on product detail pages below laptop width. Leave empty to use the desktop featured image and gallery.
   */
  mobileGallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional illustrated section (e.g. fold / unfold). Rendered only when an image is set.
   */
  howItWorks?: {
    heading?: string | null;
    image?: (number | null) | Media;
    caption?: string | null;
  };
  industries?: (number | Industry)[] | null;
  capabilities?: (number | Capability)[] | null;
  materials?: (number | Material)[] | null;
  finishes?: (number | Finish)[] | null;
  applications?: (number | Application)[] | null;
  specifications?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Second spec table shown next to Specification.
   */
  accessories?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dimensioned engineering drawing shown in its own section.
   */
  technicalDrawing?: (number | null) | Media;
  dimensions?: {
    length?: string | null;
    width?: string | null;
    height?: string | null;
    notes?: string | null;
  };
  loadCapacity?: string | null;
  surfaceTreatment?: string | null;
  brochures?: (number | Brochure)[] | null;
  model3D?: (number | null) | ThreeDAsset;
  isConfigurable?: boolean | null;
  configurationOptions?:
    | {
        group: string;
        options?:
          | {
              label: string;
              value: string;
              priceImpactNote?: string | null;
              /**
               * Hex color to tint this option pill (Color groups), e.g. #3d47ff.
               */
              swatch?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  layout?:
    | (
        | HomeHeroBlock
        | HomeIndustriesBlock
        | HomeProcessBlock
        | PageHeroBlock
        | CapabilityListingBlock
        | IndustryListingBlock
        | ProductListingBlock
        | BrochureListingBlock
        | BlogListingBlock
        | ContactRFQBlock
        | HeroBlock
        | LogoCloudBlock
        | BenefitsBlock
        | FeatureGridBlock
        | ThreeDShowcaseBlock
        | StatsBlock
        | ProcessStepsBlock
        | CaseStudyBlock
        | CTABlock
        | FAQBlock
        | LeadFormBlock
        | RichTextBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-families".
 */
export interface ProductFamily {
  id: number;
  title: string;
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  industryFocus?: (number | Industry)[] | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  painPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  solutions?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedCapabilities?: (number | Capability)[] | null;
  relatedProducts?: (number | Product)[] | null;
  caseStudies?: (number | CaseStudy)[] | null;
  brochures?: (number | Brochure)[] | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  title: string;
  slug: string;
  processType:
    | 'machining'
    | 'sheet-metal'
    | 'fabrication'
    | 'welding'
    | 'bending-forming'
    | 'surface-treatment'
    | 'assembly'
    | 'engineering-design'
    | 'other';
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  capacityNotes?: string | null;
  toleranceNotes?: string | null;
  typicalOutputs?:
    | {
        label: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  clientName: string;
  industry?: string | null;
  summary: string;
  featuredImage?: (number | null) | Media;
  relatedProducts?: (number | Product)[] | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | HomeHeroBlock
        | HomeIndustriesBlock
        | HomeProcessBlock
        | PageHeroBlock
        | CapabilityListingBlock
        | IndustryListingBlock
        | ProductListingBlock
        | BrochureListingBlock
        | BlogListingBlock
        | ContactRFQBlock
        | HeroBlock
        | LogoCloudBlock
        | BenefitsBlock
        | FeatureGridBlock
        | ThreeDShowcaseBlock
        | StatsBlock
        | ProcessStepsBlock
        | CaseStudyBlock
        | CTABlock
        | FAQBlock
        | LeadFormBlock
        | RichTextBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  primaryLabel?: string | null;
  primaryHref?: string | null;
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  previewHeading?: string | null;
  previewItems?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeIndustriesBlock".
 */
export interface HomeIndustriesBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  items: {
    title: string;
    meta?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeIndustries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeProcessBlock".
 */
export interface HomeProcessBlock {
  eyebrow?: string | null;
  heading: string;
  steps: {
    title: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  primaryLabel?: string | null;
  primaryHref?: string | null;
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityListingBlock".
 */
export interface CapabilityListingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilityListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustryListingBlock".
 */
export interface IndustryListingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'industryListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListingBlock".
 */
export interface ProductListingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  showFilters?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrochureListingBlock".
 */
export interface BrochureListingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brochureListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListingBlock".
 */
export interface BlogListingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactRFQBlock".
 */
export interface ContactRFQBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactRFQ';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  actions?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary' | 'text') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  heading?: string | null;
  logos: {
    name: string;
    logo: number | Media;
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  heading: string;
  intro?: string | null;
  benefits: {
    title: string;
    description: string;
    icon?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading: string;
  features: {
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeDShowcaseBlock".
 */
export interface ThreeDShowcaseBlock {
  heading: string;
  description?: string | null;
  modelFile?: (number | null) | Media;
  fallbackImage?: (number | null) | Media;
  cameraPreset?: ('orbit' | 'static' | 'exploded') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeDShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  stats: {
    value: string;
    label: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  heading: string;
  steps: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyBlock".
 */
export interface CaseStudyBlock {
  heading?: string | null;
  caseStudies?: (number | CaseStudy)[] | null;
  featuredImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  content?: string | null;
  backgroundImage?: (number | null) | Media;
  actions?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary' | 'text') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  faqs?: (number | Faq)[] | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock".
 */
export interface LeadFormBlock {
  heading: string;
  description?: string | null;
  submitLabel?: string | null;
  fields: {
    name: string;
    label: string;
    fieldType: 'text' | 'email' | 'phone' | 'textarea' | 'select';
    required?: boolean | null;
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  title: string;
  slug: string;
  materialType?: ('mild-steel' | 'stainless-steel' | 'aluminum' | 'galvanized-steel' | 'other') | null;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes".
 */
export interface Finish {
  id: number;
  title: string;
  slug: string;
  finishType?: ('powder-coating' | 'painting' | 'galvanizing' | 'polishing' | 'brushing' | 'raw' | 'other') | null;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "three-d-assets".
 */
export interface ThreeDAsset {
  id: number;
  title: string;
  slug: string;
  format: 'glb' | 'gltf' | 'usdz' | 'fbx' | 'obj' | 'other';
  thumbnail?: (number | null) | Media;
  products?: (number | Product)[] | null;
  scale?: number | null;
  defaultCamera?: {
    x?: number | null;
    y?: number | null;
    z?: number | null;
  };
  /**
   * Select a reusable lighting preset. Editing the preset updates every linked model automatically.
   */
  lightingPreset?: (number | null) | LightingPreset;
  /**
   * Controls shown in the 3D viewer for this model. Clip-based actions play a matching animation clip in the GLB (e.g. an action named "fold").
   */
  viewerActions?:
    | (
        | 'fold-unfold'
        | 'open-close'
        | 'extend-retract'
        | 'exploded-view'
        | 'play-pause'
        | 'reset-view'
        | 'auto-rotate'
        | 'hotspots'
      )[]
    | null;
  viewerNotes?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Reusable scene lighting and renderer settings. Editing a preset updates every linked 3D asset.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lighting-presets".
 */
export interface LightingPreset {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  environment: {
    source: 'preset' | 'hdri' | 'none';
    preset?:
      | ('apartment' | 'city' | 'dawn' | 'forest' | 'lobby' | 'night' | 'park' | 'studio' | 'sunset' | 'warehouse')
      | null;
    /**
     * Upload an .hdr or .exr environment map in Media, then select it here.
     */
    hdri?: (number | null) | Media;
    intensity?: number | null;
    rotation?: {
      x?: number | null;
      y?: number | null;
      z?: number | null;
    };
  };
  background: {
    mode: 'color' | 'environment' | 'transparent';
    color?: string | null;
    intensity?: number | null;
    blur?: number | null;
  };
  lights?: {
    ambient?: {
      enabled?: boolean | null;
      intensity?: number | null;
      color?: string | null;
    };
    hemisphere?: {
      enabled?: boolean | null;
      intensity?: number | null;
      skyColor?: string | null;
      groundColor?: string | null;
    };
    directionalLights?:
      | {
          name: string;
          enabled?: boolean | null;
          intensity?: number | null;
          color?: string | null;
          position?: {
            x?: number | null;
            y?: number | null;
            z?: number | null;
          };
          castShadow?: boolean | null;
          shadowMapSize?: number | null;
          shadowBias?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  contactShadows?: {
    enabled?: boolean | null;
    opacity?: number | null;
    blur?: number | null;
    color?: string | null;
    far?: number | null;
    scale?: number | null;
    positionY?: number | null;
  };
  renderer: {
    toneMapping: 'none' | 'linear' | 'reinhard' | 'cineon' | 'aces-filmic' | 'agx' | 'neutral';
    exposure?: number | null;
    shadows?: boolean | null;
    shadowMapType?: ('basic' | 'percentage' | 'soft' | 'variance') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  parent?: (number | null) | Page;
  layout?:
    | (
        | HomeHeroBlock
        | HomeIndustriesBlock
        | HomeProcessBlock
        | PageHeroBlock
        | CapabilityListingBlock
        | IndustryListingBlock
        | ProductListingBlock
        | BrochureListingBlock
        | BlogListingBlock
        | ContactRFQBlock
        | HeroBlock
        | LogoCloudBlock
        | BenefitsBlock
        | FeatureGridBlock
        | ThreeDShowcaseBlock
        | StatsBlock
        | ProcessStepsBlock
        | CaseStudyBlock
        | CTABlock
        | FAQBlock
        | LeadFormBlock
        | RichTextBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  slug: string;
  campaign?: string | null;
  conversionGoal?: string | null;
  layout?:
    | (
        | HomeHeroBlock
        | HomeIndustriesBlock
        | HomeProcessBlock
        | PageHeroBlock
        | CapabilityListingBlock
        | IndustryListingBlock
        | ProductListingBlock
        | BrochureListingBlock
        | BlogListingBlock
        | ContactRFQBlock
        | HeroBlock
        | LogoCloudBlock
        | BenefitsBlock
        | FeatureGridBlock
        | ThreeDShowcaseBlock
        | StatsBlock
        | ProcessStepsBlock
        | CaseStudyBlock
        | CTABlock
        | FAQBlock
        | LeadFormBlock
        | RichTextBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  author?: (number | null) | User;
  publishedAt?: string | null;
  excerpt: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines".
 */
export interface Machine {
  id: number;
  name: string;
  slug: string;
  capability: number | Capability;
  machineType: string;
  brand?: string | null;
  model?: string | null;
  summary?: string | null;
  capacity?: string | null;
  maxWorkpieceSize?: string | null;
  materialsSupported?: (number | Material)[] | null;
  typicalOutputs?: (number | Product)[] | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  machineStatus?: ('active' | 'planned' | 'maintenance' | 'retired') | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  message?: string | null;
  source?: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'closed';
  assignedTo?: (number | null) | User;
  consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfqs".
 */
export interface Rfq {
  id: number;
  quoteReference?: string | null;
  status: 'new' | 'reviewing' | 'needs-info' | 'quoted' | 'won' | 'lost' | 'archived';
  buyerName: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  industry?: (number | null) | Industry;
  productInterest?: string | null;
  relatedProducts?: (number | Product)[] | null;
  relatedCapabilities?: (number | Capability)[] | null;
  lead?: (number | null) | Lead;
  quantity?: string | null;
  targetDeliveryDate?: string | null;
  message: string;
  uploadedFiles?: (number | Media)[] | null;
  configurationData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourcePage?: string | null;
  assignedTo?: (number | null) | User;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formName: string;
  email?: string | null;
  source?: string | null;
  page?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null);
  lead?: (number | null) | Lead;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  avatar?: (number | null) | Media;
  rating?: number | null;
  featured?: boolean | null;
  relatedCaseStudy?: (number | null) | CaseStudy;
  relatedProduct?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brochures';
        value: number | Brochure;
      } | null)
    | ({
        relationTo: 'lighting-presets';
        value: number | LightingPreset;
      } | null)
    | ({
        relationTo: 'three-d-assets';
        value: number | ThreeDAsset;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'machines';
        value: number | Machine;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'product-families';
        value: number | ProductFamily;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'finishes';
        value: number | Finish;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'rfqs';
        value: number | Rfq;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brochures_select".
 */
export interface BrochuresSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brochureType?: T;
  summary?: T;
  coverImage?: T;
  products?: T;
  industries?: T;
  capabilities?: T;
  isPublic?: T;
  requiresLeadCapture?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lighting-presets_select".
 */
export interface LightingPresetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  environment?:
    | T
    | {
        source?: T;
        preset?: T;
        hdri?: T;
        intensity?: T;
        rotation?:
          | T
          | {
              x?: T;
              y?: T;
              z?: T;
            };
      };
  background?:
    | T
    | {
        mode?: T;
        color?: T;
        intensity?: T;
        blur?: T;
      };
  lights?:
    | T
    | {
        ambient?:
          | T
          | {
              enabled?: T;
              intensity?: T;
              color?: T;
            };
        hemisphere?:
          | T
          | {
              enabled?: T;
              intensity?: T;
              skyColor?: T;
              groundColor?: T;
            };
        directionalLights?:
          | T
          | {
              name?: T;
              enabled?: T;
              intensity?: T;
              color?: T;
              position?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              castShadow?: T;
              shadowMapSize?: T;
              shadowBias?: T;
              id?: T;
            };
      };
  contactShadows?:
    | T
    | {
        enabled?: T;
        opacity?: T;
        blur?: T;
        color?: T;
        far?: T;
        scale?: T;
        positionY?: T;
      };
  renderer?:
    | T
    | {
        toneMapping?: T;
        exposure?: T;
        shadows?: T;
        shadowMapType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "three-d-assets_select".
 */
export interface ThreeDAssetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  format?: T;
  thumbnail?: T;
  products?: T;
  scale?: T;
  defaultCamera?:
    | T
    | {
        x?: T;
        y?: T;
        z?: T;
      };
  lightingPreset?: T;
  viewerActions?: T;
  viewerNotes?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  parent?: T;
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        homeIndustries?: T | HomeIndustriesBlockSelect<T>;
        homeProcess?: T | HomeProcessBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        capabilityListing?: T | CapabilityListingBlockSelect<T>;
        industryListing?: T | IndustryListingBlockSelect<T>;
        productListing?: T | ProductListingBlockSelect<T>;
        brochureListing?: T | BrochureListingBlockSelect<T>;
        blogListing?: T | BlogListingBlockSelect<T>;
        contactRFQ?: T | ContactRFQBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        threeDShowcase?: T | ThreeDShowcaseBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        caseStudy?: T | CaseStudyBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  primaryLabel?: T;
  primaryHref?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  previewHeading?: T;
  previewItems?:
    | T
    | {
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeIndustriesBlock_select".
 */
export interface HomeIndustriesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  items?:
    | T
    | {
        title?: T;
        meta?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeProcessBlock_select".
 */
export interface HomeProcessBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  primaryLabel?: T;
  primaryHref?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityListingBlock_select".
 */
export interface CapabilityListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustryListingBlock_select".
 */
export interface IndustryListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListingBlock_select".
 */
export interface ProductListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  showFilters?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrochureListingBlock_select".
 */
export interface BrochureListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogListingBlock_select".
 */
export interface BlogListingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactRFQBlock_select".
 */
export interface ContactRFQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  contactEmail?: T;
  contactPhone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  media?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        openInNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        name?: T;
        logo?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeDShowcaseBlock_select".
 */
export interface ThreeDShowcaseBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  modelFile?: T;
  fallbackImage?: T;
  cameraPreset?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyBlock_select".
 */
export interface CaseStudyBlockSelect<T extends boolean = true> {
  heading?: T;
  caseStudies?: T;
  featuredImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  backgroundImage?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        openInNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  faqs?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock_select".
 */
export interface LeadFormBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  submitLabel?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        fieldType?: T;
        required?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  campaign?: T;
  conversionGoal?: T;
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        homeIndustries?: T | HomeIndustriesBlockSelect<T>;
        homeProcess?: T | HomeProcessBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        capabilityListing?: T | CapabilityListingBlockSelect<T>;
        industryListing?: T | IndustryListingBlockSelect<T>;
        productListing?: T | ProductListingBlockSelect<T>;
        brochureListing?: T | BrochureListingBlockSelect<T>;
        blogListing?: T | BlogListingBlockSelect<T>;
        contactRFQ?: T | ContactRFQBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        threeDShowcase?: T | ThreeDShowcaseBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        caseStudy?: T | CaseStudyBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedAt?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientName?: T;
  industry?: T;
  summary?: T;
  featuredImage?: T;
  relatedProducts?: T;
  challenge?: T;
  solution?: T;
  results?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        homeIndustries?: T | HomeIndustriesBlockSelect<T>;
        homeProcess?: T | HomeProcessBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        capabilityListing?: T | CapabilityListingBlockSelect<T>;
        industryListing?: T | IndustryListingBlockSelect<T>;
        productListing?: T | ProductListingBlockSelect<T>;
        brochureListing?: T | BrochureListingBlockSelect<T>;
        blogListing?: T | BlogListingBlockSelect<T>;
        contactRFQ?: T | ContactRFQBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        threeDShowcase?: T | ThreeDShowcaseBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        caseStudy?: T | CaseStudyBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  processType?: T;
  summary?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  capacityNotes?: T;
  toleranceNotes?: T;
  typicalOutputs?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines_select".
 */
export interface MachinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  capability?: T;
  machineType?: T;
  brand?: T;
  model?: T;
  summary?: T;
  capacity?: T;
  maxWorkpieceSize?: T;
  materialsSupported?: T;
  typicalOutputs?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  machineStatus?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  painPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedCapabilities?: T;
  relatedProducts?: T;
  caseStudies?: T;
  brochures?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-families_select".
 */
export interface ProductFamiliesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  industryFocus?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  productType?: T;
  productFamily?: T;
  summary?: T;
  description?: T;
  breadcrumb?: T;
  industryLabel?: T;
  categoryLabel?: T;
  keySpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  mobileGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        heading?: T;
        image?: T;
        caption?: T;
      };
  industries?: T;
  capabilities?: T;
  materials?: T;
  finishes?: T;
  applications?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  accessories?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  technicalDrawing?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
        notes?: T;
      };
  loadCapacity?: T;
  surfaceTreatment?: T;
  brochures?: T;
  model3D?: T;
  isConfigurable?: T;
  configurationOptions?:
    | T
    | {
        group?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              priceImpactNote?: T;
              swatch?: T;
              id?: T;
            };
        id?: T;
      };
  relatedProducts?: T;
  relatedCaseStudies?: T;
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        homeIndustries?: T | HomeIndustriesBlockSelect<T>;
        homeProcess?: T | HomeProcessBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        capabilityListing?: T | CapabilityListingBlockSelect<T>;
        industryListing?: T | IndustryListingBlockSelect<T>;
        productListing?: T | ProductListingBlockSelect<T>;
        brochureListing?: T | BrochureListingBlockSelect<T>;
        blogListing?: T | BlogListingBlockSelect<T>;
        contactRFQ?: T | ContactRFQBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        threeDShowcase?: T | ThreeDShowcaseBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        caseStudy?: T | CaseStudyBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  materialType?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes_select".
 */
export interface FinishesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  finishType?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  message?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfqs_select".
 */
export interface RfqsSelect<T extends boolean = true> {
  quoteReference?: T;
  status?: T;
  buyerName?: T;
  company?: T;
  email?: T;
  phone?: T;
  industry?: T;
  productInterest?: T;
  relatedProducts?: T;
  relatedCapabilities?: T;
  lead?: T;
  quantity?: T;
  targetDeliveryDate?: T;
  message?: T;
  uploadedFiles?: T;
  configurationData?: T;
  sourcePage?: T;
  assignedTo?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formName?: T;
  email?: T;
  source?: T;
  page?: T;
  lead?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  avatar?: T;
  rating?: T;
  featured?: T;
  relatedCaseStudy?: T;
  relatedProduct?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navigation?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary' | 'text') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Large brand wordmark displayed over the footer grid artwork.
   */
  headline: string;
  emailLabel?: string | null;
  emailAddress?: string | null;
  phoneLabel?: string | null;
  phoneNumbers?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  linkGroups?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletterHeading?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterButtonLabel?: string | null;
  /**
   * Use {privacyLink}, {googlePrivacy}, and {terms} to place the editable links.
   */
  newsletterPrivacyText?: string | null;
  newsletterPrivacyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  addresses?:
    | {
        address: string;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Used only in the website navigation. SVG is recommended.
   */
  logo?: (number | null) | Media;
  /**
   * Used only for browser tabs and bookmarks. Upload a separate square image.
   */
  favicon?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  defaultTitle: string;
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  robots?: ('index,follow' | 'noindex,follow' | 'noindex,nofollow') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  links?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'x' | 'youtube' | 'tiktok' | 'other';
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  headline?: T;
  emailLabel?: T;
  emailAddress?: T;
  phoneLabel?: T;
  phoneNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  linkGroups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  newsletterHeading?: T;
  newsletterPlaceholder?: T;
  newsletterButtonLabel?: T;
  newsletterPrivacyText?: T;
  newsletterPrivacyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  addresses?:
    | T
    | {
        address?: T;
        phone?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultImage?: T;
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}